### PR TITLE
update sabre/xml + ignore composer.lock file

### PR DESCRIPTION
**Pull request by it-can**

### CODE REVIEW

**Comment by brtdv** [comment]
Shouldn't the composer.lock file be included in the repo to ensure compability with all required libraries?

**Comment by it-can** [comment]
Yeah its not a big issue, https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by RamonSmit** [comment]
It's no problem, because this is a _package_. For a big project, I would advise to keep the lockfile. But for a single package as this, not really needed.

**Comment by brtdv** [comment]
Okay, in that case, I updated the sabre/xml package to v2.1 like in your pull request, but kept the `composer.lock` file since it seems relevant to me to keep package versions locked to certain version numbers so that everything keeps working (e.g. if breaking changes are introduced to sabre/xml).

Somehow I'm not able to merge your pull request (probably because you've removed your cloned repo?) but I added the same changes to 23a20526aa655eb1c90aca2f07d7d2100027c06a... (tagged as v1.4)

**Pull request closed without merging**
