### PR TITLE
new UnitCodes and possibility to set InvoicePeriod per InvoiceLine

### PR DESCRIPTION
**Pull request by jbputit**
Hi Bert,

just added UnitCodes for year, month and piece and added possibility to set InvoicePeriod for each InvoiceLine.

Thanks,
  Jens

### CODE REVIEW

**Comment by brtdv** [comment]
Hi @jbputit, thanks so much! I've merged your changes on master and released them as v1.10.1

**Comment by jbputit** [comment]
Hi Bert, I cannot see a release v1.10.1, in only see v1.10 but I am not sure if the problem is on my side.

**Comment by brtdv** [comment]
So... apparently I forgot to push the v1.10.1 tag 😱 
Sorry about that. Should be OK now :-)

**Comment by jbputit** [comment]
excellent, thank you!

**Pull request merged**
